//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVotingSystemForCollege
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCandidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCandidate()
        {
            this.tblResults = new HashSet<tblResult>();
        }
    
        public int CandidateId { get; set; }
        public string CandidateName { get; set; }
        public Nullable<int> ElectionId { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public Nullable<int> VoteObtained { get; set; }
    
        public virtual tblElection tblElection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResult> tblResults { get; set; }
    }
}
