//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVotingSystemForCollege
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblElection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblElection()
        {
            this.tblCandidates = new HashSet<tblCandidate>();
            this.tblResults = new HashSet<tblResult>();
        }
    
        public int ElectionId { get; set; }
        public string ElectionName { get; set; }
        public string ElectionStartDate { get; set; }
        public string ElectionEndDate { get; set; }
        public Nullable<int> NoOfCandidate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCandidate> tblCandidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResult> tblResults { get; set; }
    }
}
