//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVotingSystemForCollege
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResult
    {
        public int VoteId { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> ElectionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual tblCandidate tblCandidate { get; set; }
        public virtual tblElection tblElection { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
